---
name: a-share-decision-system
description: "A股投资决策体系合并版 v1.0(2026.7.5) — L1-L5总控+全量扫描Stage 0-7+择股7步法[0]-[9]。合并自: 小齐股市框架v4.3 / L1-L4框架v3.1 / 择股7步法v1.5.4"
triggers:
  - 择股
  - 选股
  - 帮选股
  - 帮我选
  - 找标的
  - 扫描
  - 扫一遍
  - 拉一遍
  - 全量扫描
  - 板块扫描
  - 赛道扫描
  - 板块还有机会吗
  - 全板块拉一遍
  - 赛道全量
  - 框架分析
  - 完整分析
  - 能不能买
  - 分析一下
  - 帮我看看
  - 有什么
  - 有哪些
  - 怎么样
  - 7步法
  - 7-step
  - thesis
  - 深度分析
  - 单票分析
  - 概念标签
  - 标准分类
  - 分类优化
  - 标准化
  - 主营构成
  - 营收占比
  - 赛道权重
  - 概念权重
  - 上下游拆解
  - 怎么看
  - BK
  - 板块
  - 赛道
version: 1.0.0
---

# A股投资决策体系 — AI 精确执行手册

> **合并自**: 小齐股市框架 v4.3 + L1-L4 决策流水线 v3.1 + 择股7步法 v1.5.4
> **合并日期**: 2026.7.5
> **设计原则**: 每一条规则都是可执行、可验证的指令，不是人类笔记。

---

# PART 0 — 元规则（META-RULES）

> **AI 注意：** 这是预处理层。每次触发本 skill 时，先读完 PART 0，再进入任何流程。违反任一条 = 执行无效。

---

## 0.1 数据铁律：记忆 ≠ 实时数据

**来源**: 择股7步法 v1.5.2，事故教训 — 金盘科技(2026.7.2)

```
[DATA_CHECK] — Step [1]/[2]/[3] 执行前强制断言：

  ASSERT: 数据来源 == "API实时拉取"       // 禁止使用记忆中的历史数据
  ASSERT: 持仓信息已与用户最新确认         // SOUL.md 超过3个交易日 → 主动询问
  ASSERT: 未引用任何"上次分析时"的数值      // 价格/PE/趋势/持仓比例 ≠ 记忆数据
```

**记忆只能存什么**: 框架规则、用户偏好、方法论、静态行业知识
**记忆禁止存什么**: 股票价格、MA方向、持仓比例、PE、增速等时变数据

**持仓引用规范**:
- SOUL.md 标注"用户确认"日期，超过 3 个交易日 → 主动询问确认
- 用户口头告知的最新持仓 > SOUL.md 书面记录

---

## 0.2 反作弊规则（Anti-Cheating）

**来源**: 小齐股市框架 v4.2.1，Iron Rule 0

| # | 规则 | 检测方式 |
|---|------|---------|
| AC-1 | 每 Stage 输出必须包含**具体数字**（进入数/淘汰数/通过率%） | 输出中搜索不到数字 → BLOCK |
| AC-2 | 禁止"我先快速扫一眼" — 只有完整扫和不扫 | 关键词检测 |
| AC-3 | **Stage 0-5b 期间禁止出现 A/B+/B/B-/C/D 评级** — 违禁词: `A级\|B+\|B-\|B级\|C级\|重仓\|观察仓\|基准仓` | 正则检测 |
| AC-4 | 最终结论必须有完整**漏斗数字链**（每个 Stage 占一个节点，零淘汰也必须出现） | 缺少中间环节 → BLOCK |
| AC-5 | 没有 BK 代码提取全量成分股 → 等于没扫 | 全量扫描场景专用 |

**违规模式库（7次）**:

| # | 日期 | 症状 | 根因 | 防复发检查 |
|---|------|------|------|-----------|
| 1 | 6.3 | PE陷阱跳过周期判定 | 急于完成分析 | 每次 PE 前确认 [周期分类] 已完成 |
| 2 | 6.6 | SP500数据不验证 | 用旧数据 | [DATA_CHECK] |
| 3 | 6.24 | 新雷能不拉K线说"在MA20上方" | 凭记忆 | [DATA_CHECK] |
| 4 | 6.25 | 三次图快给错结论 | 追求速度 | 每 Step 确认后再进下一步 |
| 5 | 7.2 | 金盘科技说"最强趋势"实为真DOWN | 凭旧记忆 | [DATA_CHECK] + 先拉K线再判断 |
| 6 | 7.2 | 持仓不确认直接引用 SOUL.md | 未确认用户最新口头告知 | 持仓引用前先确认最新状态 |
| 7 | 7.3 | 13只股5分钟自称"走完7步法" | 跳 Stage | 检查清单逐项打勾，漏项必须标注 |

---

## 0.3 执行纪律总则

```
[1] 不可跳步 — 每 Stage/Step 必须输出 CONFIRM: 后才能进入下一步
[2] 最新数据优先 — 每次触发重新拉取，禁止引用旧分析
[3] 输出标准化 — 每个步骤必须遵循固定的输出模板格式
[4] 跳步声明 — 若因技术限制无法执行某步，必须标注"跳步原因+影响范围+请用户确认"
[5] 断点续做 — 若流程中断，从最后完成的 Stage 继续，不从头开始
```

---

## 0.4 数据完整性强制校验 — Iron Rule 24

> **v1.1 新增 (2026.7.5)**: Hermes 产出数据 JSON 后、Claude 进入框架分析前，强制逐项校验。
> **设计原则**: 金融分析必须数据说话，不许推理、不许猜测、不许"待拉取"。

### 分工定义

```
Hermes (研究员):  数据采集 → 12 个必填字段 → 标准化 JSON
Claude (基金经理): 数据校验 → L0-L5 分析 → 评分+仓位+结论
Hindsight:       框架规则 + 违规记录 + 用户偏好（禁止存时变数据）

两个独立防线，AND 关系:
  数据不全 + 逻辑对 = 结论不可靠 → 退回 Hermes 补数据
  数据全 + 逻辑错 = 结论不可靠 → 检查框架触发规则
  数据全 + 逻辑对 = 可以出结论
```

### 12 个必填字段

Hermes 每次出分析 JSON 必须包含以下字段。缺一项 → JSON 退回，不进框架。

```
===== 基础信息 (3项, 来源: CSV直接读取) =====
[ ] code          — 股票代码 (如 300395.SZ)
[ ] name          — 股票名称
[ ] market        — 市场 (上交所/深交所/北交所)

===== 财务数据 (4项, 来源: East Money API / 新浪网页 / 同花顺) =====
[ ] 8-13季度营收/净利  — 逐季拆出, 不依赖累计数据
[ ] GPM/NP率趋势      — 至少最近 4 个季度
[ ] 资产负债表         — 应收/应付/存货/在建工程/固定资产/商誉/有息负债
[ ] 现金流表           — 经营CFO/资本开支/FCF, 最近 4 个季度

===== 排雷数据 (5项, 来源: 财报附注 / 同花顺股东页) =====
[ ] NonRec%          — 非经常性损益 ÷ |归母净利|, 绝对值分母
[ ] 商誉/净资产       — BS 商誉科目 ÷ 净资产
[ ] 有息负债/净资产   — (短期借款+长期借款+应付债券) ÷ 净资产
[ ] 大股东质押率      — 东方财富/同花顺 股东质押页面
[ ] 审计意见          — 年报审计报告 → 标准无保留 / 非标 → 直接淘汰
```

### 数据缺失规范

```
禁止: "待拉取" / "数据缺" / "N/A" / 空白字段
允许: "已尝试 [来源A]/[来源B]/[来源C] 均失败, 原因: [具体原因]"

例:
  正确: "NonRec%: [数据缺失 — 已尝试东方财富利润表/新浪财报页/同花顺THS,
         均因代理拦截失败, 建议手动截图财报'非经常性损益'章节]"
  错误: "NonRec%: 待拉取"
```

### 校验流程

```
Hermes 交 JSON
  → Claude 读 PART 0.4
  → 逐项勾对 12 个字段:
      [✓] 基础信息 3/3
      [✓] 财务数据 4/4
      [✗] 排雷数据 3/5 — 缺大股东质押率 + 审计意见
  → 缺 2 项 → 退回 Hermes, 不回话:
      "DATA_CHECK FAILED: 缺 大股东质押率 / 审计意见。补充后重新提交。"
  → 12/12 齐全 → 进入 L0-L5 分析
```

### 赛道扫描 — 全量覆盖强制规则

> **v1.3 新增 (2026.7.5)**: 赛道扫描禁止抽样。每只成分股必须逐只过 Stage。

```
[COVERAGE_CHECK] — 赛道扫描专属:

  Stage 3 K线+财务:
    输入: [N] 只 → 必须产出 [N] 份 K线+财务数据
    缺任意一只 → JSON 退回:
      "COVERAGE FAILED: Stage 3 只拉了 [X]/[N] 只。必须逐只全量，禁止'分析X/Y只'。"

  Stage 5 PEG旁路:
    输入: [N] 只 → 必须产出 [N] 份 PEG + NP增速≤3×CAGR 判定
    缺任意一只 → JSON 退回

  Stage 5b 增长陷阱:
    输入: [N] 只 → 必须产出 [N] 份 ROE+营收+PE 三条判定

  禁止词: "已分析 X/Y 只" (X < Y) / "sample" / "代表性"
  允许: "数据源不可达 — 已尝试 [A/B/C], 标注 [数据缺失]"

  铁律: 全量 = 全量。没有"我拉几只代表性的就够了"。
        "不扫 = 没扫" (AC-5)
```

```

# PART 1 — 总控决策流水线（L1-L5 ORCHESTRATOR）

> **角色**: 不做计算，只做路由。确保按 L1→L2→L3→L4→L5 顺序执行。
> **来源**: L1-L4 框架 v3.1

---

## 1.0 L0 — W&W 情绪温度计（v1.1 新增 2026.7.5）

> **定位**: 刹车，不是油门。亢奋时减速，恐惧时不加速。
> **位置**: 挂在 L1 前面，作为压缩系数，不直接做仓位决策。
> **数据源**: `~/AppData/Local/hermes/scripts/ww_indicator.py`（akshare，每日拉取）
> **交叉验证**: 2026.7.5 完成 6 因子 akshare 内部一致性验证（0%偏差）
> **敏感性**: 2026.7.5 完成 F2 CSI300 PE → 全A PE 测试（W&W 仅变化 +2.6，不敏感）
> **历史验证**: 2026.7.5 完成 6 个关键顶底回测（5/6 正确识别，顶部识别精准）

### L0 → 压缩系数映射表

| W&W 读数 | 区间标签 | 压缩系数 | 设计依据 |
|----------|---------|---------|---------|
| 0-20 | Very Bullish | ×1.0 | 极度恐惧，不压缩（2011.9 20.7） |
| 20-40 | Bullish | ×1.0 | 偏恐惧，不压缩（2019.1 32.2、2024.9 29.8） |
| 40-60 | Neutral | ×1.0 | 中性，不干预（2024.2 量化崩盘仅 40.6，误杀风险） |
| 60-80 | Bearish | ×0.6 | 偏亢奋，中等压缩 |
| 80-100 | Very Bearish | ×0.4 | 极度亢奋，重压缩（2015.4 97.1、当前 90.3） |

### 关键设计决策

```
1. Bullish 区 ×1.0 不压缩 — 指标告诉你"便宜了"，不该再打折扣
2. Neutral 区 ×1.0 不干预 — 指标没态度时不出手（2024.2 量化崩盘仅 40.6 的教训）
3. 80-100 只给 ×0.4，不给 ×0 — 2015年 W&W 见顶97.1后市场还涨了6周，空仓会踏空
4. 非对称设计 — 恐惧端不放大仓位（刹车不是油门），亢奋端只收缩不禁止
5. L2/L3 系数暂不乘法链叠加 — 等数据管道打通后再并轨（现阶段只用 L0×L1）
```

### 执行规则

```
每次触发 skill: 运行 ww_indicator.py 获取最新 W&W → 查表得压缩系数
禁止: 从 SOUL.md 记忆引用 WW 读数（融资数据每日更新）
```

---

## 1.1 入口路由 — 用户意图 → 执行路径

```
ON_USER_INPUT:
  // === 单票分支 ===
  IF 意图 包含 ("能不能买"|"分析XX") AND 用户指定了具体股票代码/名称:
    → [AUTO-PRE] 自动前置 L0 → L1 → L2 → L3              ← v1.1: L0必须跑ww_indicator.py
    → 进入 L4 PART 2（跳过 Stage 0-2，标的已确定）
    → 从 Stage 3 开始（拉K线+财务）
    → Stage 3.5 → Stage 4 → Stage 5 → Stage 5b
    → Stage 6C 择股7步法（独立执行模式，[0]-[9]完整）
    → Stage 6.5 质量闸门
    → 最后 L5

  // === 赛道扫描分支 ===
  IF 意图 包含 ("扫描XX"|"择股"|"选股"|"BK"|"板块"|"赛道") AND 未指定具体股票:
    → [AUTO-PRE] 自动前置 L0 → L1 → L2 → L3
    → 进入 L4 PART 2（完整 Stage 0-7 全量扫描）
    → 最后 L5

  IF 意图 明确为 "仓位上限"|"SP500"|"美股风险":
    → 仅 L1（L1 执行时自动先拉 L0）  ← v1.1

  IF 意图 明确为 "宏观"|"六象限"|"宏观方向":
    → 仅 L2

  IF 意图 明确为 "XX赛道该不该买"|"产业周期"|"T1-T4":
    → 仅 L3

  IF 意图 明确为 "7步法"|"单票分析"|"深度分析"|"XX怎么样":
    → 仅 PART 3 [0]-[9]（独立执行模式）

  IF 意图 明确为 "明天怎么操作"|"交易计划"|"买点":
    → 仅 L5

  IF 用户说 "跳过L1-L3直接看XX":
    → 跳过前置，直接进 L4
    → 但 L0 仍必须执行（Iron Rule 23: W&W 只压缩不跳过）  ← v1.1

  IF 用户说 "跳过L0直接L1":
    → 标注 "[WARN] L0跳过，Iron Rule 23 豁免（用户明确指令）"
    → L1_有效上限 = L1_SP500_cap × 1.0（无L0压缩）
```

---

## 1.2 L1 — 仓位上限（SP500风控，v4.1条件介入）

```
定位: 紧急刹车，不是日常温度计。只在极端风险时介入。
流向: L0 → L1 (L0先刹车，L1在极端风险时一票否决)

输入: L0 W&W压缩系数 + SP500风控模型状态
执行:
  1. 运行 ww_indicator.py → 获取最新W&W → 查§1.0映射表得 L0_compression
  2. 运行 compute_sp500_score_v4.py → 获取 SP500风险级别 → 得 L1_等级 + L1硬帽子

传导规则 (v4.1):
  IF L1_等级 == L4(地狱) OR L5(炼狱):          // 全球危机 — 有因果链
      L5_实操帽子 = L1_硬帽子(35%或15%)          // L1一票否决，L0不叠加
  ELSE:                                         // 日常 — SP500数据不判断A股仓位
      L5_实操帽子 = L0_WW压缩 × 100%             // L1不参与，只看本土情绪

  设计原则:
    L1回归否决权。平时不管，极端时一票否决。
    SP500模型判断A股日常仓位没有因果依据（场景2A股独涨/场景3A股独跌）。
    A股日常仓位由L0(本土情绪) + L4(选股质量)决定。

当前状态 (2026.7.5):
  L1等级 = L3(困难) → 不介入
  L0_WW = ×0.4 (W&W=90.3)
  L5_实操帽子 = 0.4 × 100% = 40%
  // 对比旧公式: 0.4 × 70% = 28% (差异12pp = L1的"噪音税")

v4升级 (2026.7.5):
  脚本: compute_sp500_score_v4.py
  变更: VIX→RV20替代(×1.2安全系数) + z-score全部364周滚动窗口
  注意: 当Excel滞后>3周时Score可能偏差0.3-0.5, 需交叉验证
```

---

## 1.3 L2 — 宏观象限（six-quadrant-model）

```
角色: 中国宏观环境分类器。输出仓位上限 + "不碰什么"。
定位: 否定判断(不碰什么) > 肯定判断(该买什么)

输入: 无（独立判断中国宏观，不依赖L0/L1）
数据源: CPI/PPI/PPIRM/PMI(统计局) + Z-Credit/Z-Monetary(用户PDF)
       信用维度依赖用户月度PDF — akshare/East Money无法替代

六象限 → 仓位映射:
  宽信用扩张          80%    热
  信用修复型再通胀     80%
  低通胀稳增长        80%
  紧信用放缓          55%    温
  供给冲击型滞胀       50%    ← 当前 (病)
  通缩式下行          60%    冷

DC滞回机制: 退出条件满足后 → 再等1个月确认 → 只调一次
  回测: DC年化+10.93% vs CK+9.99% vs 买入持有+7.97%
  核心原则: 宁可滞后一个月，不要追着信号跑

输出（两项独立输出，AND关系）:
  ┌──────────────────────────────────────────┐
  │ L2_定量: 仓位上限 = [X]%                      │
  │   进入 L5 定量帽子 = min(L0×100%, L2_仓位上限) │
  │                                              │
  │ L2_定性: 不碰清单 = [赛道/行业列表]              │
  │   硬约束 — 不受L0/L1帽子数字影响，始终生效         │
  │   由 L3 翻译为具体 BK 代码后进入 Stage 0-7       │
  │                                              │
  │ L2_定性: 肯定方向 = [赛道/行业列表] (参考)         │
  │ CONFIRM: L2完成                                │
  └──────────────────────────────────────────┘

L0/L2 冲突仲裁规则 (v1.2新增):
  IF L0(Bullish/VeryBullish ×1.0) AND L2(滞胀/通缩/紧信用):
    → L2_不碰清单优先于L0帽子数字
    → 定量可以宽松(帽子给100%)，定性不能放松(不碰清单照常生效)
    → L5_定性约束 > L0_帽子数字
  理由: 情绪可以骗人，宏观不会。L0测冷热，L2测病因。

当前状态 (2026.7):
  状态: 供给冲击型滞胀(第5月)
  定量: 50% 仓位上限
  定性: 不碰成本敏感型中游制造业(PPI-PPIRM=-1.9pp)
  退出条件: 6个条件全不满足 — 短期不会退出
```

---

## 1.4 L3 — 产业择时（l3-industry-cycle-timing）

```
角色: L2宏观状态 → BK代码翻译器。把"不碰成本敏感型中游"翻译成具体赛道名单。

输入: L2_不碰清单 + L2_肯定方向
输出:
  ┌──────────────────────────────────────────┐
  │ L3_不碰BK: [BKxxxx, BKxxxx, ...]            │
  │   ← L2定性约束 → 具体BK代码                  │
  │   例: 光伏(BKxxxx) — 硅料成本端有色+化工       │
  │       电池(BKxxxx) — 锂电材料，下游压价         │
  │       基础化工(BKxxxx) — 原油成本+产能过剩      │
  │                                              │
  │ L3_保留BK: [BKxxxx, BKxxxx, ...]            │
  │   ← L2肯定方向 → 具体BK代码                   │
  │   例: 半导体设备(BKxxxx) — 高附加值，定价权强    │
  │       AI芯片(BKxxxx) — 国产替代逻辑独立         │
  │                                              │
  │ 翻译依据: PPI-PPIRM行业敏感度映射表             │
  │ CONFIRM: L3完成                               │
  └──────────────────────────────────────────┘

冲突规则: L2 和 L3 打架时 → 信 L3（产业信号 > 宏观信号）

### L3 角色A — z-score 产业周期信号 (定性风向标)

```
定位: 定性风向标，非定量输入。
  T4逃顶 / T2反转 方向判断可信。
  9-Bucket具体收益率数字不可信 (样本11次中9次连续)。
  个股z-score噪声大，暂不用于个股筛选。

数据源: 创业板300只 6指标 (合同负债/CAPEX/现金购买/存货/在建工程/资产周转率)
  65季历史 z-score → Lead_z / Lag_z / Divergence
  来源: East Money财务API, 季度更新

T1-T4 四层信号:
  T1(高置信底): Lead_z<-1.0 + Lag_z<-0.5 → 2次/极高置信      ← 不参与筛选
  T2(拐点底):   分歧转正 + Lag_z<-0.2       → 3次/中高置信
  T3(拐点顶):   分歧转负 + Lag_z>+0.2       → 3次/中高置信    ← 不参与筛选
  T4(高置信顶): Δdiv<-0.8 + Lag_z>0        → 3次/极高置信

当前 (26Q1): T2已触发(弱), Δdiv=+0.18(弱反转), Lead内部分化(采购↑订单↓)
  → 弱反转, 等Q2合同负债确认

板块级用途 (挂入 Stage 2.1):
  T4触发 → 该板块跳过扫描 ("T4逃顶: 历史3/3, 每次跌幅>45%")
  T2触发 + Δdiv>0.5(强反转) → 板块绿灯, 优先扫描
  Δdiv<0.2(弱反转) → 板块正常扫描, 但不升级优先级
```

当前状态 (2026.7.5): [已建]
  L3_滞胀期BK黑名单_v1.2.csv — 5511只, 三层分类体系
  层级1: SW1行业级 — 医药/电子/计算机/军工等自动分类
  层级2: SSHY细分级 — 通用设备→不碰, 专用设备→保留等
  层级3: GPM兜底+豁免 — GPM>=30%→保留, <20%→不碰, 特殊豁免
  已挂载至 Stage 2.0 黑名单预过滤。
  每行含完整来源追溯 (L3_来源列: SW1=保留/SSHY细分/GPM阈值)
```
```

---

## 1.5 L4 → L5 仓位传导

```
L5 输入结构 (v1.2): 定量帽子 + 定性约束，AND关系

  [定量] L5_仓位帽子:
    日常: min(L0_WW×100%, L2_仓位上限)       // L1不介入，L2和L0取紧
    极端: L1_硬帽子                           // L1=L4/L5时一票否决
    例: min(40%, 50%) = 40% (L0更紧)

  [定性] L5_不碰约束:
    = L2_不碰清单 → L3翻译 → BK代码黑名单
    不受定量帽子数字影响，始终生效
    例: 即使帽子100%，也不能买不碰清单里的东西

  L5_实操仓位 = min(L4_战略上限, L5_仓位帽子)
  且: 标的 ∉ L5_不碰约束 (硬过滤)

L0-L2 传导链:
  L0: W&W=90.3 → ×0.4 → 40% 帽子
  L1: SP500 L3 → 不介入
  L2: 滞胀 → 50% 帽子 + 不碰成本敏感型中游
  L3: [空缺] 待BK翻译
  → L5定量帽子 = min(40%, 50%) = 40%
  → L5定性约束 = L3黑名单预过滤 (5511只, Stage 2.0自动排除[不碰])
```
  完整公式 (L2/L3 数据管道打通后):
    日常: L5_实操帽子 = L0_WW压缩 × L2_宏观调整 × L3_赛道调整 × 100%
    极端: L5_实操帽子 = L1_硬帽子  // L4/L5全局危机

设计原则:
  L1回归否决权 — SP500数据不判断A股日常仓位
  A股日常仓位由L0(本土情绪) + L4(选股质量)决定
```

---

## 1.6 L5 — 交易执行（a-share-trading-plan）

```
角色: 持仓执行引擎。择股归L4，执行归L5。
定位: 永远 ≤ L4战略上限。只能向下调，不能向上加。

输入: L4 标的选择 + 战略仓位上限 + L0-L2定量帽子 + L3定性约束

执行规则（详见 PART 3 [8] + L5_交易执行引擎文档_v3.3.md）:

  [买] 分批建仓:
    大黑马(8-15%上限, ABC三批): MA20拐头→回踩确认→全多头加速
    周期反转(5%上限, AB两批):   MA20站上放量→站稳5日确认
    硬约束: A/B间隔≥3交易日; 永不加仓亏钱头寸

  [卖] 双确认制 A+B (铁律第一条):
    A条件(框架层 v3.1): 强A(清仓级) / 弱A(减仓级) / 不触发
    B条件(技术层 v3.3): 跌破MA20 + MA20拐头下行
      强B: MA20已拐头下行 → 全清
      弱B: MA20仍在上升 → 按5日斜率分四档(见PART 3 [8]子检查5)
      恐慌日修正: WW<20或CSI300跌>3% → 弱B降级观察
    A+B同时满足 → 执行。仅A不满足B → 设止盈不动手。
    仅B不满足A → 按B内部分级执行。

  [管] 追踪止损 + CVaR缩放:
    追踪止损 v3.1: 浮盈≥20%触发, 梯度收紧(1.5→1.0→0.8×ATR)
    CVaR缩放: 振幅因子自动适配波动环境
    Tier 2进攻: 六条件全满→叠加+10-15%(不超过L2总上限)

  [纪律] 现金就是持仓:
    没有更好的机会，现金是最优持仓。
    仓位上限是上限，不是目标。

输出模板:
  ┌──────────────────────────────────────────┐
  │ L5 交易计划                                │
  │ 标的: [名称/代码]   L4战略上限: [X]%         │
  │ L0-L2定量帽子: [X]%                        │
  │ 买入: [触发条件+价格区间+批次比例]             │
  │ 止损: 8%/12% = [价格]/[价格]                │
  │ 卖出: A条件=[描述] B条件=[MA20状态]          │
  │ CONFIRM: L5完成                             │
  └──────────────────────────────────────────┘
```

---

# PART 2 — 全量扫描流水线（Stage 0-7）

> **来源**: 小齐股市框架 v4.3
> **触发场景**: 用户说"择股"/"扫描XX板块"/"赛道全量"
> **前置条件**: PART 1 的 L1-L3 已执行（除非用户明确跳过）

---

## Stage 0 — Q1 报告 5 级分数制

```
入口: 用户指定的板块/赛道范围
数据源: 全市场概念分类表_v3.csv（Hermes 维护）或东方财富 Q1 季报数据
处理: 按 2026 Q1 报告核心指标打分，5 级制筛选

Q1 五级分数制判定标准（三指标加权）:
  ① Q1 营收增速 YoY（权重 35%）
  ② Q1 扣非净利润增速 YoY（权重 35%）
  ③ Q1 GPM 绝对值 + 环比变化（权重 30%）

五级定义:
  L5（强烈推荐）: 三指标全 > 20%，GPM 不降 → 优先进入全量扫描
  L4（推荐）:     两指标 > 20%，GPM 不降 → 进入全量扫描
  L3（中性）:     至少一指标 > 10%，无重大恶化 → 进入全量扫描
  L2（审慎）:     三指标 0-10%，或单季恶化 > 30% → 仅在有催化剂时进入
  L1（回避）:     营收负增长 + 净利润负增长，或 GPM 连续两季恶化 > 5pp → 不进入扫描

规则:
  - Q1 报告分数决定择股范围，L1 级不进入后续
  - 禁止主观挑行业或凭记忆给分
  - 若 CSV 中无 Q1 数据，标注 "[数据缺失]" 并降一级为 L3

输出模板:
  ┌─────────────────────────────────────┐
  │ Stage 0 完成                         │
  │ 全量成分股: [N] 只                    │
  │ L5: [X]只  L4: [Y]只  L3: [Z]只     │
  │ L2(需催化剂): [A]只  L1(回避): [B]只  │
  │ 进入 Stage 1: [X+Y+Z] 只              │
  │ CONFIRM: Stage 0 完成                 │
  └─────────────────────────────────────┘
```

---

## Stage 1 — 全量成分股提取

```
入口: Stage 0 筛选结果
处理: 从 BK 板块代码提取全量成分股
规则:
  - BK 代码必须先验证再提取
  - 参考 references/bk-extraction-guide.md (dat文件格式 + SSHY过滤)
  - 禁止手动挑股票

输出模板:
  ┌─────────────────────────────────────┐
  │ Stage 1 完成                         │
  │ BK代码: [BKxxxx]                     │
  │ 成分股: [N] 只                        │
  │ CONFIRM: Stage 1 完成                 │
  └─────────────────────────────────────┘
```

---

## Stage 2 — L3 黑名单预过滤 + 概念关联度过滤

```
入口: Stage 1 成分股列表
数据源: L3_滞胀期BK黑名单_v1.2.csv + 全市场概念分类表_v3.csv

===== 2.0 L3 黑名单预过滤 (v1.2新增, 2026.7.5) =====

数据源: C:\Users\Administrator\Desktop\股票库\L3_滞胀期BK黑名单_v1.2.csv
  columns: code, name, SW1, SSHY, 主赛道, Tier, GPM, PE, 市值, 概念标签, L3_判定, L3_来源
  覆盖: 5511 只 A 股

过滤规则:
  对每只 Stage 1 成分股:
    IF 标的 L3_判定 == "[不碰]":
      → 直接淘汰 (标记: L3黑名单—[具体原因见L3_来源])
    IF 标的 L3_判定 == "[T0限制]":
      → 保留但标记 T0 (流动性/政策硬约束，不进重仓)
    IF 标的 L3_判定 == "[强周期]":
      → 保留但标记 强周期 (进入 Stage 3.5 周期拦截)
    IF 标的 不在 CSV 中:
      → 无罪推定，通过 (标注: [未收录])
    ELSE:
      → 通过

  豁免: 无。L3 不碰清单是 L2 宏观定性约束的硬翻译，不可跳过。

===== 2.05 L3 z-score 板块级方向过滤 (v1.2新增, 2026.7.5) =====

数据源: L3 产业周期择时 (l3-industry-cycle-timing skill)
  创业板300只 6指标 Lead-Lag z-score → T1-T4信号
  定位: 定性风向标 — T4逃顶/T2反转方向可信, 具体数字不可信

板块级规则:
  IF L3_T4触发(高置信顶):
    → 整个板块跳过扫描，不进 Stage 2.1
    → 标注: "L3 T4逃顶信号: 历史3/3触发, 每次跌幅>45%"
    → 不可跳过。T4是L3置信度最高的信号。

  IF L3_T2触发 + Δdiv > +0.5(强反转):
    → 板块级绿灯，优先扫描
    → 标注: "L3 T2强反转: 类比2018Q4 Δdiv=+0.68 → 36月+166%"

  IF L3_T2触发 + Δdiv < +0.2(弱反转, 当前):
    → 板块正常扫描，不升级优先级
    → 标注: "L3 T2弱反转: Δdiv=+0.18, 等Q2合同负债确认"

  IF 无 L3信号:
    → 按正常流程

===== 2.1 概念关联度过滤 =====

数据源: 全市场概念分类表_v3.csv 的"概念标签"列 + "主赛道"列
处理: 按概念关联度 + 主赛道匹配度打分，过滤不相关标的

过滤规则（三条件 OR 关系，满足任一即通过）:
  条件 A — 主赛道直接匹配:
    标的"主赛道"字段 == 用户指定的赛道名 → 直接通过，关联度 = Tier1
  
  条件 B — 概念标签关键词匹配:
    标的"概念标签"字段 与 目标赛道的核心概念有 ≥ 2 个交集 → 通过，关联度 = Tier2
    
  条件 C — 上下游传导关联（v4.3 新增）:
    标的在 MULTI_TRACK 中与目标赛道存在上下游关系 → 通过，关联度 = Tier3
    例: 设备 ← IDC产业链上游，材料 ← 电池产业链上游

淘汰条件:
  - 三条件全不满足 → 淘汰（与目标赛道无任何关联）
  - 营收占比 < 5% 的主赛道 → 降为 Tier3（名义关联，实质不相关）

元数据标签一次性标注（全局复用）:
  MULTI_TRACK:   标的涉及的所有关联赛道（取 CSV"概念标签" + "主赛道"并集）
  CHAIN_POSITION: 在每条关联赛道中的产业链位置（上游/中游/下游/应用端）

输出模板:
  ┌──────────────────────────────────────────────┐
  │ Stage 2 完成                                   │
  │ 输入: [N] 只                                   │
  │ [2.0] L3黑名单:                                │
  │   → 淘汰(不碰): [X]只  T0限制: [Y]只  强周期: [Z]只 │
  │ [2.05] L3 z-score板块方向:                      │
  │   → T4逃顶(跳过板块): [是/否]                    │
  │   → T2反转(绿灯): [是/否]                       │
  │ [2.1] 概念关联度:                               │
  │   → Tier1(直接匹配): [A]只  Tier2(概念交集): [B]只 │
  │   → Tier3(上下游关联): [C]只  淘汰(无关联): [D]只   │
  │ 通过: [剩余] 只                                 │
  │ CONFIRM: Stage 2 完成                           │
  └──────────────────────────────────────────────┘
```

---

## Stage 3 — 多周期 K 线 + 财务拉取

```
入口: Stage 2 幸存者
处理: 月线→周线→日线（这个顺序不许颠倒）+ 财务数据拉取
规则:
  - Monthly K-line BEFORE daily MA20
  - 生命周期标签差异化阈值，非装饰性标签
  - 关键词打分不能替代人工精判

输出模板:
  ┌─────────────────────────────────────┐
  │ Stage 3 完成                         │
  │ 输入: [N] 只                          │
  │ 淘汰: [N] 只                          │
  │ → 真DOWN: X 只 (MA20斜率<-0.5 + MA30 DOWN)
  │ → 月线透支: Y 只                       │
  │ → 量价背离: Z 只                       │
  │ 幸存: [N] 只                          │
  │ CONFIRM: Stage 3 完成                 │
  └─────────────────────────────────────┘
```

---

## Stage 3.5 — 周期股强制拦截 ⚠️ v4.3 核心新增

**位置**: Stage 3 之后 → 7 步法之前
**入口场景**: 全量扫描（Stage 3 幸存者逐只执行） / 单票分析（Stage 3 完成后直接进入）
**目的**: 防止 8 月 Q2 财报批量更新后，周期顶部暴利 → TTM PE 被动下降 → 低 PE 当价值股买入

### 强周期 PE 陷阱 — 两种触发路径

> **路径 A — 存量 PE 陷阱**：TTM PE 因利润周期性冲顶而被动下降，低 PE 不是便宜。
> **路径 B — 增量 PE 陷阱**（⑥ Q2 预告 PE 骤降）：Q2/H1 预告发布后 PE 骤降，表象"变便宜"，实际是周期顶部利润滞后反映。

```
对每只 Stage 3 幸存者:

IF Step E 判定为 "强周期" OR "中周期":
  ├── 禁用绝对 PE 估值
  ├── 改用 PB 历史分位 + PS 分位判断估值位置
  │
  ├── [路径 A] IF 强周期 AND PE < 15:            // PE=15 阈值（pe15-backtest.md 回测）
  │     ├── 审查①: QoQ 利润增速 > 前两季均值?     [YES/NO]
  │     ├── 审查②: 行业资本开支 YoY < 0?          [YES/NO]
  │     ├── 审查③: PB 分位 < 30%?                  [YES/NO]
  │     │          (运行: python3 pb_percentile.py CODE)
  │     │
  │     ├── 三项全 YES → "周期底部复苏" → 不淘汰，走 PB/PS 估值
  │     └── 任一项 NO → "周期顶部 PE 陷阱" → 淘汰
  │
  └── [路径 B] IF Q2/H1 预告发布后 PE 骤降 ≥ 40%:  // ⑥ Q2预告PE骤降
        ├── 强制使用 PB/PS 分位估值，禁用 PE
        ├── 附加判定:
        │   CFO/NP < 0.5 → "利润含金量不足，PE骤降是假修复"
        │   QoQ 增速连续两个季度放缓 → "周期顶部确认"
        ├── 任一条触发 → 淘汰
        └── 均不触发 → 以 PB/PS 估值继续，标记 [Q2预告PE骤降]

  // 案例: 江波龙(301308) H1预告 → PE 48x→21x + CFO/NP=-0.74 + QoQ放缓 → 路径B淘汰

ELSE IF PE < 15 AND 营收增速 < 5%:
  └── "价值陷阱" (PEG = 15/5 = 3.0 > 框架 PEG≤1.0) → 淘汰
      // 非周期行业的低 PE 低增长，无限横盘
```

### CFO/NP < 0.5 处理（三类豁免）

```
IF CFO/NP < 0.5 连续两季:
  ├── 豁免 ①: 固定资产/总资产 > 30% AND 在建工程 YoY > 50% → "产能扩张期" 豁免
  ├── 豁免 ②: 存货/总资产 > 40% AND 存货 YoY > 营收 YoY → "战略性备货" 豁免
  ├── 豁免 ③: 合同负债 YoY > 50% → "项目型确认" 豁免（Q4 集中确认导致 Q2 占比异常）
  └── 不属以上三类 → 淘汰/降级
```

### 适用范围边界

| 适用（强周期） | 不适用（弱周期/非周期） |
|--------------|---------------------|
| 存储、化工、煤炭、有色、新能源上游、船舶、养殖 | 消费、医药、公用事业、必选消费品 |

```
输出模板:
  ┌─────────────────────────────────────┐
  │ Stage 3.5 周期拦截完成                │
  │ 输入: [N] 只                          │
  │ 强周期标记: [X] 只  中周期标记: [Y] 只  │
  │                                     │
  │ [路径A] PE<15 存量PE陷阱:              │
  │   触发二次审查: [Z] 只                  │
  │   → 周期底部复苏(通过): [A] 只          │
  │   → 周期顶部PE陷阱(淘汰): [B] 只        │
  │                                     │
  │ [路径B] Q2预告PE骤降≥40%:              │
  │   触发PB/PS强制替代: [C] 只            │
  │   → 附加淘汰(CFO/NP<0.5+QoQ放缓): [D]只 │
  │                                     │
  │ CFO/NP豁免触发: [E] 只                 │
  │ 价值陷阱淘汰(PE<15+增速<5%): [F] 只     │
  │ 幸存: [N-淘汰] 只                     │
  │ CONFIRM: Stage 3.5 完成               │
  └─────────────────────────────────────┘
```

---

## Stage 4 — 月线透支检验

```
入口: Stage 3.5 幸存者
数据源: K线 API（东方财富/同花顺/掘金量化）
处理: 月线透支 + MA20/MA30 位置检验

月线透支判定标准:
  ① 月线连阳透支:
     月线 ≥ 4 连阳（近4个月月线全红）→ 短期涨幅透支，标记
     月线 ≥ 6 连阳 → 直接淘汰（历史规律：A股极少6月连阳后不回调）
  
  ② 月线乖离率检验:
     月线 MA20 乖离率 > 25% → 月线级别超买，标记
     月线 MA30 乖离率 > 40% → 月线严重超买，淘汰

  ③ 月线量价背离:
     月线价格创新高 but 月线成交量萎缩 > 30%（vs 前高月份）→ 量价背离，标记

规则:
  - 放量回调不是买点（Iron Rule 12）
  - 量价配合是趋势的呼吸（Iron Rule 10）
  - 标记项触发 ≥ 2 条 → 淘汰

输出模板:
  ┌─────────────────────────────────────┐
  │ Stage 4 完成                         │
  │ 输入: [N] 只                          │
  │ → 连阳透支淘汰: [X]只                  │
  │ → 乖离率超标淘汰: [Y]只                │
  │ → 量价背离淘汰: [Z]只                  │
  │ 幸存: [N-X-Y-Z] 只                    │
  │ CONFIRM: Stage 4 完成                 │
  └─────────────────────────────────────┘
```

---

## Stage 5 — PE 陷阱检测 + PEG 旁路（非周期品专项）

```
入口: Stage 4 幸存者
处理: Stage 3.5 已处理强周期/中周期的 PE 陷阱 + 价值陷阱，本阶段仅处理剩余的非周期品

===== 5.0 PE 阈值检查 =====

标准门槛:
  正常赛道: PE ≤ 23
  扩张赛道: PE ≤ 28 + PEG ≤ 0.7
  注: PE<15+增速<5% 价值陷阱已在 Stage 3.5 拦截；强周期PE陷阱已在 3.5 拦截

===== 5.1 PEG 旁路 (v1.3新增, 2026.7.5) =====

设计理由: 框架 Step E3 识别了"成长被误判为高估"的分类错误。
  capex密集+研发前置+利润释放滞后 → PE天然偏高不是因为贵, 是因为利润结构。
  PEG旁路不是特赦某一赛道, 是让框架纠正自己的分类错误。

触发条件 (三条全满足 → 走PEG旁路, 不因PE超标淘汰):
  ① 生命周期 = 成长期 / 导入期 (Stage 6A 已标注, 非成熟期/衰退期)
  ② PEG ≤ 1.0 AND NP增速 ≤ 近3年CAGR × 3.0
     // 第2项约束防止"单季暴增拉低PEG"假通过
     // 上限×3.0: 增速可以快但不能离谱——单季225% vs 3年CAGR 15% → 差15倍, PEG=0.24是假象
     // 例: 通富微电 Q1 NP+225%, 近3年CAGR=15% → 225% > 45%(15%×3.0) → 不满足
  ③ 板块逻辑 = 国产替代 / 技术垄断 (L3_来源字段含"技术定价权"/"国产替代"或概念标签匹配)

PEG旁路结果:
  → 通过: 标记 [PE超标-PEG旁路], 进入 Stage 5b 继续
    Stage 7 估值分析中强制使用 PEG + FCF PEG 双校验
  → 不通过(PEG>1.0或NP增速不达标): 淘汰

按PE直接淘汰 (不适用PEG旁路):
  成熟期/衰退期 + PE > 23 → 淘汰
  成长期/导入期 + PE > 28 + PEG旁路不通过 → 淘汰

输出模板:
  ┌─────────────────────────────────────┐
  │ Stage 5 完成                         │
  │ 输入: [N] 只                          │
  │ → PE直接超标淘汰: [A]只                │
  │ → PEG旁路通过(标记进入5b): [B]只         │
  │ → PEG旁路不通过(淘汰): [C]只            │
  │ → PE达标: [D]只                        │
  │ 幸存: [B+D] 只                         │
  │ CONFIRM: Stage 5 完成                  │
  └─────────────────────────────────────┘
```

---

## Stage 5b — 增长陷阱 + 重资产 ROE 联合审查

> **来源**: 手册 Step D4-⑤（增长陷阱）+ Step D4-⑧（重资产ROE联合审查）
> **设计理由**: 两条规则核心判定条件相同（ROE<5% + PE>40x + 增收不增利），合并为一个 Stage 前置拦截，不进 7 步法

```
入口: Stage 5 幸存者

判定树（逐只执行）:

  IF 营收增速 > 20%
     AND 近 3 年 ROE 不升反降（或持续 < 5%）
     AND PE(TTM) > 40x:

    ├── 非重资产行业 → 直接淘汰（⑤ 增长陷阱）
    │    案例: 某软件股 营收+25% / ROE 6%→4%→3% / PE 60x → 淘汰
    │
    └── 重资产行业(IDC/电网/设备/封测/IDM):
          ├── ROE 6-10% + PE < 30x + 产能投产在即 → 观察豁免
          │    标注: "等待ROE拐点确认"，不进 7 步法重仓评估
          │    案例: 某电网股 ROE 8.2% + PE 25x + H2投产 → 观察
          │
          └── 不满足豁免条件（ROE<5% 或其他两条触发）→ 淘汰（⑧ 重资产联合审查）
               案例: 奥飞数据 ROE 3.7% + PE 55x + 营收+31.1%且ROE连降 → 淘汰

逻辑: 营收增长靠 capex 堆出来，ROE 反而被资产膨胀压制
      → "越增长越不赚钱" = 经典 malinvestment
      → 不等"利润拐点"，直接淘汰

输出模板:
  ┌─────────────────────────────────────┐
  │ Stage 5b 增长陷阱+重资产ROE审查完成     │
  │ 输入: [N] 只                          │
  │ → 增长陷阱淘汰(非重资产): [A] 只         │
  │ → 重资产: 触发联合审查: [B] 只           │
  │     → 淘汰(三条全中): [C] 只             │
  │     → 观察豁免(ROE 6-10%+PE<30x): [D]只 │
  │ 标记不触发: [E] 只                      │
  │ 幸存(含观察): [N-A-C] 只                │
  │ CONFIRM: Stage 5b 完成                 │
  └─────────────────────────────────────┘
```

---

## Stage 6A — 元数据预处理

> **执行时机**: Stage 5 完成后，对每只幸存者执行。一次性标注，后续所有 Stage 复用。

```
入口: Stage 5 幸存者列表
数据源: 全市场概念分类表_v3.csv + 多赛道权重.json

处理:
  1. 生命周期标签标注（每只必标一个）:
     导入期: 营收增速 > 30% + 行业渗透率 < 20% + PE 可能为负
     成长期: 营收增速 15-30% + 行业渗透率 20-50% + PE 偏高
     成熟期: 营收增速 5-15% + 行业渗透率 > 50% + PE 稳定
     衰退期: 营收增速 < 5% + 行业渗透率 > 80% + PE 偏低
  
  2. 概念权重计算:
     从 CSV 获取"概念标签"列，计算:
       core_weight = 概念标签与目标赛道交集数 / 目标赛道核心概念总数
       edge_weight  = 边缘概念标签数（CSV 中标记为"边缘概念 ×1"的概念）
     权重总计 = core_weight × 0.7 + min(edge_weight × 0.3, 0.3)
  
  3. 赛道权重复核:
     从 多赛道权重.json 读取标的的营收分拆权重
     若 JSON 中有精确权重 → 以此为准覆盖 CSV 估算值

规则:
  - 生命周期标签 ≠ 装饰性标签，会影响后续 Stage 6C Step E（周期位置）、Step C（增速预期）
  - 标签差异化的阈值: 成长期可容忍更高 PE（≤28），成熟期严格按 PE≤23

输出模板:
  ┌─────────────────────────────────────┐
  │ Stage 6A 元数据预处理完成              │
  │ 输入: [N] 只                          │
  │ 生命周期分布:                          │
  │   导入期: [A]只  成长期: [B]只          │
  │   成熟期: [C]只  衰退期: [D]只          │
  │ 概念权重达标(≥0.5): [X]只              │
  │ 权重不足(<0.5): [Y]只 → 标记但不淘汰    │
  │ CONFIRM: Stage 6A 完成                 │
  └─────────────────────────────────────┘
```

---

## Stage 6B — 板块细分拆解

> **执行时机**: Stage 6A 完成后。对每只 Stage 6A 输出者执行。确定子赛道归属，避免"伪分散化"。

```
入口: Stage 6A 输出（含生命周期标签 + 概念权重）
数据源: 多赛道权重.json + 全市场概念分类表_v3.csv + Web Search 行业研报

处理:
  1. 子赛道归属判定:
     方案 A: 从 多赛道权重.json 读取精确营收占比 → 归属到营收占比最大的子赛道
     方案 B: 若 JSON 无此标的，从 CSV 的"概念标签"推断 → 报告不确定性，标注 [CSV推断]
     
  2. 竞争格局快照（每子赛道生成一张表）:
     | 公司 | GPM | 营收增速 | ROE | 市占率(估) |
     |------|-----|---------|-----|-----------|
     | 目标公司 | X% | X% | X% | X% |
     | 同子赛道对手A | X% | X% | X% | X% |
     | 同子赛道对手B | X% | X% | X% | X% |

  3. 同族子赛道聚类:
     将 Stage 5 幸存者按子赛道归属分组
     标记: 同一"族"子赛道内的标的 → Stage 7 用 Iron Rule 16 约束总仓位

规则:
  - 子板块拆解 BEFORE 评级（Iron Rule 3）
  - 同一子赛道内的标的，后续 7步法评分要横向可比

输出模板:
  ┌─────────────────────────────────────┐
  │ Stage 6B 板块细分拆解完成              │
  │ 子赛道分布:                           │
  │   [子赛道A]: [X]只                     │
  │   [子赛道B]: [Y]只                     │
  │   独立赛道(无同类): [Z]只               │
  │ 同族标记: [列表]                       │
  │ CONFIRM: Stage 6B 完成                 │
  └─────────────────────────────────────┘
```

---

## Stage 6C — 单票深度分析（调用 PART 3 择股7步法）

```
入口: Stage 6B 输出列表
执行:
  框架调用模式:
    [0] NonRec% 前置闸门 → 由本 PART 执行（见下方）
    [1]-[9] → 委托给 PART 3 执行
  输出时标注: "执行模式: 框架调用"
```

### Stage 6C [0] — NonRec% 前置闸门（框架级，MANDATORY FIRST）

```
NonRec% = 非经常性损益 ÷ |归母净利润|      // 绝对值分母，避免亏损股负净利混乱

IF NonRec% < 10%   → 盈利干净，通过
IF NonRec% 10-30%  → 需用扣非 PE/ROE，标记
IF NonRec% > 80%   → 直接淘汰
```

**前置排雷（与本步骤同级）**:

**(1) 商誉/净资产 > 30%**:
```
→ 仓位上限自动降一级: A→B+, B+→B, B→C
→ 商誉/净资产 > 30% + 审计意见非标 → 联合触发淘汰
```

**(2) 资产负债率红线**（使用有息负债/净资产，非总负债率）:

| 行业类型 | 红线 | 触发动作 |
|----------|------|----------|
| 制造业/周期股 | 有息负债/净资产 > 70% | 标记高风险 |
| 消费类 | 有息负债/净资产 > 60% | 标记高风险 |

```
CFO/NP < 0.5 连续两季 + 红线触发 → 直接进入观察池，禁止重仓
行业豁免: 重资产(IDC/电网/机场/高速公路) + CFO/NP > 1 → 豁免至 80%
```

**(3) 暴雷引用**:
```
大股东质押率 > 50% → 标记，Lazy-Check 注明
审计意见非标 → 直接淘汰
```

---

## Stage 6.5 — 质量闸门四问（二次审查）

```
[6.5-Q1] 这个生意的质量配得上评级吗？
[6.5-Q2] 和同赛道其他标的横向对比如何？
[6.5-Q3] 如果是我的钱我会买吗？
[6.5-Q4] 有没有遗漏的关键信息？（数据缺口）

任一答案为"否":
  → 手动降级至观察仓 (≤10%)，不执行原评分对应的重仓配置
  → 标注: 闸门否决 — [原因]
```

---

## Stage 7 — 最终仓位输出

```
输入: Stage 6 评分 + Stage 6.5 闸门判断
规则:
  // 流动性约束
  IF 日均成交额 < 3000万 → max 仓位 = 2%

  // 子赛道集中度控制
  IF 多只标的属于同一"族"子赛道:
    同族总仓位上限 = MAX(各标的仓位上限) × 1.2  // Iron Rule 16: 伪分散化是真集中

  // L4 战略上限
  战略仓位上限 = 评分→仓位映射(见 PART 4.3)

输出模板:
  ┌─────────────────────────────────────┐
  │ Stage 7 最终仓位输出                   │
  │ 漏斗: [S0]→[S1]→[S2]→[S3]→[S3.5]→[S4]→[S5]→[S5b]→[S6A]→[S6B]→[S6C]→[S6.5]→[S7] │  ← 12 Stage，每个占一个节点，零淘汰不可跳过
  │ 标的: [名称/代码]                      │
  │ L4 战略仓位上限: [X]%                  │
  │ 流动性约束: [有/无]                    │
  │ 子赛道集中度: [OK/触发 cap]            │
  │ CONFIRM: 全量扫描完成                   │
  └─────────────────────────────────────┘
```

---

# PART 3 — 择股7步法 [0]-[9]

> **来源**: 7-step-thesis v1.5.4，格式已修正
> **两种模式**:
> - **框架调用模式** (Stage 6C): [0] 由 PART 2 执行，本 PART 从 [1] 开始
> - **独立执行模式** (用户单票分析): 执行完整 [0]-[9]

---

## [EXECUTION DISCIPLINE]

每条规则都是可执行的指令，不是人类笔记。Agent 必须逐条执行，不可将规则视为"阅读材料"。每执行完一个 [Step] 必须输出 `CONFIRM:` 确认。所有 `[DATA_CHECK]` 断言必须在 API 实时拉取数据后通过，禁止使用记忆中的数据。

---

## [0] NonRec% 前置校验 — 仅独立执行模式

```
执行条件: 执行模式 == "独立执行"
内容: 与 PART 2 Stage 6C [0] 完全一致
  → 框架调用时跳过本步，标注 "[0] 已由框架层执行，从 [1] 开始"
```

---

## [1] 单季度财务拆解（8-13 季度）

```
[DATA_CHECK] — 断言: 财务数据来自 API 实时拉取

输入: 最近 8-13 季度单季度财报
处理:
  1. 每季度单独拆出: 营收 / 净利 / NP 率（不依赖累计数据）
  2. 看趋势: QoQ 环比 + YoY 同比 + NP 率变化

子检查 1: 季节性归一化
  Q4 单季 vs 过去至少 3 年同期均值:
    Q4 GPM < 3年均值 5pp 以上 → 会计洗澡嫌疑
    Q4 营收 > 3年均值显著 → 年末突击确认收入嫌疑

子检查 2: 三阶营收增速校验
  近1年营收增速 / 近2年CAGR / 近3年CAGR

  三阶全 > 15% 且加速     → "加速型"（最优）
  三阶全 > 15% 但减速     → "稳定型"
  1年 > 30% 但 2/3年 < 10% → "爆发型"（一次性订单？需验证可持续性）
  1年 < 5%                → "停滞型" → 触发业绩预警

子检查 3: GPM/NP 率连续恶化预警
  连续 2 季 GPM 或 NP 率环比下行 → 扣分，纳入 Step D
  例外（以价换量）: GPM 下行但营收增速环比扩大 ≥5pp → 豁免

输出模板:
  ┌─────────────────────────────────────┐
  │ [1] 财务拆解完成                      │
  │ 增长类型: [加速/稳定/爆发/停滞]          │
  │ 季节性异常: [有/无]                    │
  │ GPM 恶化预警: [有/无]                  │
  │ CONFIRM: [1] 完成                     │
  └─────────────────────────────────────┘
```

---

## [2] 资产负债表 + 现金流

```
[DATA_CHECK] — 断言: 数据来自 API 实时拉取

输入: 最新资产负债表 + 现金流表
处理:

子检查 1: 上游下游议价权象限
  应收↓ + 应付↑ = 两头吃 → 加分
  应收↓ + 应付↓ = 对下游有议价 → 中性
  应收↑ + 应付↑ = 对上游有议价(压货) → 警惕
  应收↑ + 应付↓ = 被双向挤压 → 扣分

子检查 2: FCF（自由现金流 = 经营CFO - 资本开支）
  重资产行业(IDC/电网/设备/封测/IDM):
    FCF 连续两年为负 → 标注"融资依赖"，不自动淘汰
  轻资产行业(SaaS/设计/服务):
    FCF 连续三年为负 → 直接淘汰
  FCF > 0 且连续增长 → 加分

子检查 3: CFO/NP < 0.5 检查（对齐 Stage 3.5 三类豁免）
  产能扩张期/战略性备货/项目型确认 → 豁免
  不属三类 → 标记"利润含金量不足"，降一级

子检查 4: 合同负债双维度
  同比连续两季下降 → 下游需求走弱 → 扣分 + 标记"预收款萎缩"
  同比上升 + 环比平稳 → 订单储备健康

输出模板:
  ┌─────────────────────────────────────┐
  │ [2] 资债+现金流完成                    │
  │ 议价权: [两头吃/中性/警惕/被挤压]       │
  │ FCF: [正/负] [连续X年]                 │
  │ CFO/NP: [X.XX] [豁免/正常/预警]        │
  │ 合同负债: [健康/萎缩]                   │
  │ CONFIRM: [2] 完成                     │
  └─────────────────────────────────────┘
```

---

## [3] 技术面（月线 → 周线 → 日线，顺序不颠倒）

```
[DATA_CHECK] — 断言: K线数据来自 API 实时拉取，未使用记忆

输入: 月线 + 周线 + 日线 K线数据
处理:

子检查 1: 多周期趋势
  月线: 12m/6m/3m 收益 + 距高点 + K线形态
  周线: MA20 方向 + 趋势完整性
  日线: MA20/MA30/MA60 + 斜率 + 偏离度 + 量价配合

子检查 2: 股价历史分位
  3Y分位 > 80% AND 5Y分位 > 80% → 高位压缩: 仓位上限 × 0.5
  3Y分位 > 80% BUT 5Y分位 < 50% → 底部反弹中，不压缩
  3Y分位 < 30% → 低位区，不压缩
  ATH 距当前 > 50% + 基本面改善 → 困境反转候选，加分

子检查 3: 筹码结构
  日均换手率:
    < 2%     → 筹码稳定（加分）
    2-5%     → 正常
    5-10%    → 关注（可能松动）
    > 10%    → 异常活跃（减分）
  套牢盘占比(高成交量区间 > 当前价):
    > 60% → 上方抛压重 → 仓位上限 × 0.5
    < 30% → 解套压力轻 → 加分

子检查 4: 四类定性仓位系数

  | 判定 | 仓位系数 | 条件 |
  |------|---------|------|
  | 真DOWN | 淘汰 | MA20斜率 < -0.5 AND MA30方向 DOWN |
  | 回调机会 | × 0.3 | MA20↓ BUT MA30↑ + VP_LABEL=CORRECTION(缩量) |
  | 蓄力趋势 | × 0.7 | MA20走平(-0.5~+0.5) + MA30走平或微升 + 缩量横盘 |
  | 追高风险 | × 0.2 | 偏离MA20 > ATR阈值 OR 股价分位 > 90% |

  回调机会 if MA30 方向 DOWN → 降为真DOWN
  蓄力趋势等 MA20 重新拐头向上 → 恢复 × 1.0

输出模板:
  ┌─────────────────────────────────────┐
  │ [3] 技术面完成                        │
  │ 趋势判定: [真DOWN/回调/蓄力/追高/正常]  │
  │ 3Y分位: [X]%  5Y分位: [Y]%           │
  │ 月涨幅: [X]%  距ATH: [Y]%             │
  │ 换手率: [X]%  套牢盘: [Y]%            │
  │ 仓位系数: × [0.2/0.3/0.5/0.7/1.0]   │
  │ CONFIRM: [3] 完成                     │
  └─────────────────────────────────────┘
```

---

## [4] 产业链 + 竞争格局

```
输入: Web Search 产业数据 + 研报信息
处理:

子检查 1: 行业景气度标签
  上行: 行业整体营收增速 > 15% 且趋势向上
  平稳: 5-15%
  下行: < 5% 或连续下降

  与 Step C 交叉验证:
    公司"加速型"+行业"下行"=独立阿尔法 → 加分但小心(可能是抢份额不是行业好)
    公司"稳定型"+行业"上行"=随波逐流 → 不加分(贝塔的钱)

子检查 2: 政策风险约束

  | 类型 | 行业 | 风险 |
  |------|------|------|
  | 产能受限 | 光伏/电池/钢铁/水泥 | 天花板明确 |
  | 集采 | 仿制药/器械/耗材 | 降价压力 |
  | 反垄断 | 互联网平台/支付 | 业务边界受限 |
  | 出口壁垒 | 半导体设备/高端芯片 | 美国限制+国产替代窗口 |

  触发 → 标记，影响 Step G 最大风险判断

子检查 3: 竞争对手横向对标表

  | 公司 | GPM | 营收增速(YoY) | ROE | 市占率 |
  |------|-----|--------------|-----|--------|
  | 目标公司 | X% | X% | X% | X% |
  | 竞争对手A | X% | X% | X% | X% |
  | 竞争对手B | X% | X% | X% | X% |

  目标 GPM > 同行中位 ≥ 3pp AND ROE > 同行 ≥ 5pp → 护城河数据支撑
  目标 GPM 和 ROE 均 < 同行中位 → 无护城河 → Step B 自动降一级

输出模板:
  ┌─────────────────────────────────────┐
  │ [4] 产业链完成                        │
  │ 行业景气度: [上行/平稳/下行]            │
  │ 政策风险: [有/无] — [类型]             │
  │ 对手对标: [优势/劣势/持平]              │
  │ 阿尔法 vs 贝塔: [独立阿尔法/随波逐流/掉队]│
  │ CONFIRM: [4] 完成                     │
  └─────────────────────────────────────┘
```

---

## [5] A-G 核心论据层（100 分制 + 质量闸门）

> **这是择股7步法的核心。v1.5 标准化版，全面量化。**

---

### Step A — 生意质量（15 分/5 维度）

**A1. GPM 四档打分**:
```
> 30%       → 满分，天然享受估值溢价
18%-30%     → 合格，常规制造业，天然上限 B+
12%-18%     → 扣分，竞争激烈，严控仓位
< 12%       → 预警，红海同质化，天然上限 C
```

**A2. 产品标准化程度**:
```
非标准化(定制化/绑定场景) → 加分
高标准化(通用/大宗商品化) → 扣分
客户现场认证/二次开发需要 → 替换成本高 → 加分
```

**A3. 客户粘性 + 客户结构硬约束**:
```
高粘性: 认证周期长/技术深度绑定/数据迁移成本高 → 加分
硬约束: 前五大客户营收占比 > 50% → 即使粘性高也扣分
        To C 分散 / To B 多部门均匀分布 → 加分
```

**A4. 议价力测试**:
```
连续两轮原材料涨价周期中 GPM 未显著下滑 → 具备议价力 → 加分
原材料涨价 → GPM 随之下降 → 无议价力 → 扣分
```

**A5. 商业模式稳定性**:
```
预收型(高合同负债) > 销售型
重资产 + 高有息负债 → 扣分
```

```
CONFIRM: Step A 完成，A_score = [X]/15
```

---

### Step B — 护城河（20 分/4 类壁垒 + 硬约束）

**B1. 规模壁垒**: 市占率 + 单位固定成本
**B2. 客户壁垒**: 认证周期/排他协议/头部客户名录
**B3. 成本壁垒**: 自研自制率/自动化产线/上游锁料
**B4. 技术&品牌**: 研发费用率/发明专利/独家工艺（B端看标杆案例，C端看品牌心智）

**硬约束**:
```
≥ 2 类壁垒成立 → 可纳入重仓池
≤ 1 类壁垒     → 仅限观察仓 ≤ 10%
```

```
CONFIRM: Step B 完成，B_score = [X]/20，壁垒类型: [N] 类
```

---

### Step C — 增长引擎（15 分/4 维验证）

**C1. 增长来源拆分**: 产品维度(销量/新品类/提价?) + 下游维度(存量/新行业/海外?)
**C2. 持续性 3 验证**: 行业渗透率(>70%=天花板) + 产能匹配度 + 订单能见度(合同负债趋势)
**C3. 增速斜率**: 加速型(加分) / 稳定型(中性) / 减速型(扣分)
**C4. 贝塔 vs 阿尔法**: 公司增速 > 行业 5pp → 阿尔法(加分)；≈ 行业 → 贝塔(不加分)；< 行业 → 掉队(扣分)

```
CONFIRM: Step C 完成，C_score = [X]/15，增长类型: [加速/稳定/爆发/停滞]
```

---

### Step D — 财务质量（20 分/4 指标 + 杜邦 + 隐藏校验）

**D1. GPM 趋势**: 近 3 年平稳/上升 → 加分；连续 2 季下行 → 扣分；以价换量 → 豁免

**D2. NP 率稳定性**: ±15% 内(优秀) / ±15-30%(中性) / > ±30%(扣分)

**D3. NonRec% 校验**（对齐 [0]）:
```
< 10%   → 盈利干净，加分
10-30%  → 需用扣非，标注
> 80%   → 直接淘汰
```

**D4. ROE + 杜邦拆解**:
```
近 3 年年化 ROE ≥ 20% → 优质
近 3 年 < 10% → 扣分
杜邦三因子: 高净利率(产品壁垒)?/高周转(商业模式)?/高杠杆(负债)?
  高杠杆驱动 → 风险扣减
```

**D4 补充 — 重资产扩张期 ROE 容忍度**:

```
IF ROE < 10% AND 行业为重资产(IDC/电网/设备):
  → 不自动淘汰，触发联合审查

联合审查规则（三条全部触发 → 淘汰）:
  ① ROE < 5%（年化）
  ② PE(TTM) > 40x
  ③ 营收增速 > 20% 但 ROE 不升反降 → "增收不增利"陷阱

案例: 奥飞数据(300738) ROE 3.7% + PE 55x + 营收加速但 ROE 连降 → 全触发 → C级淘汰

通过联合审查(ROE 6-10% + PE < 30x + 产能投产在即) → 观察，等 ROE 拐点
```

**⑤ 营收加速 + ROE 停滞 = 增长陷阱**:
```
IF 营收增速 > 20% + 近 3 年 ROE 不升反降（或持续 < 5%）+ PE > 40x:
  → 直接淘汰，不等"利润拐点"

案例: 奥飞数据 营收+31.1%加速 / ROE 5.2%→3.9%→3.7%连降 / PE 55x → 市场按 AI 成长定价，实际 ROE < 劣质债券
```

**隐藏财务校验**（对齐前序步骤）:
```
CFO/NP 连续多年 > 1 → 利润含金量高
商誉/净资产 > 30% → 减值风险，降级
CFO/NP < 0.5 连续两季 → 按三类豁免审查（见 Stage 3.5）
```

```
CONFIRM: Step D 完成，D_score = [X]/20，杜邦类型: [高净利率/高周转/高杠杆]
```

---

### Step E — 周期位置（10 分/4 类周期 + 估值强制规则）

**E1. 四类周期判定**:

| 类型 | 特征 | 代表行业 |
|------|------|---------|
| 强周期 | 盈利高度依赖大宗商品/能源/资本开支 | 煤炭/有色/化工/钢铁/电力设备 |
| 中周期 | 跟随产能和政策周期 | 汽车/通用机械/半导体设备 |
| 弱周期 | 需求弹性低 | 医药/必选消费品 |
| 非周期(成长) | 技术替代/渗透率驱动 | 软件/AI/创新消费 |

**E2. 估值强制规则**:

```
强周期:
  → 禁止用低 PE 作为投资理由
  → 估值用 PB 历史分位 + PS 分位
  → 强周期 + PE < 15: 触发二次审查（见 Stage 3.5 判定树）

中周期:
  → PE 为辅助参考
  → 用 PEG + PB 交叉验证

弱周期/非周期:
  → PEG + 历史 PE 分位
  → PEG ≤ 1 具备安全边际
  → PE < 15 且 营收增速 < 5% → 价值陷阱淘汰 (PEG = 3.0)
```

**E3. 市场分类错误识别（4 种）**:

| 类型 | 症状 | 判定方法 |
|------|------|---------|
| ① 周期被误判为成长 | 半导体设备 PE 100x+ | 产能周期 + SOTP |
| ② 成长被误判为周期 | 时代电气 19x PE | SOTP 分部 > 市值 30%+ |
| ③ 重资产被误判为轻资产 | 净利润 PEG < 1 但 FCF PEG > 3 | 对比两种 PEG |
| ④ REIT/处置收益 PE 虚低 | NonRec > 30% 扣非 PE 极高 | 强制用扣非 PE |

**E4. 与 Step C 交叉验证**:
```
周期下行 → 即使短期增速快，估值和仓位同步下调
周期上行 + 公司加速 → 正常执行
```

**⑤ 营收加速 + ROE 停滞 = 增长陷阱**（已在 Step D4 中展开，此处引用）:

**⑥ Q2 预告 PE 骤降陷阱**:
```
判定方法:
  Q2 预告发布后 PE 骤降 ≥ 40%（如 48x → 21x）
  + 公司为强周期股
  + CFO/NP < 0.5 或 FCF 为负
  → PE 骤降是利润周期性冲顶的滞后反映，非估值修复
  → 强制使用 PB/PS 分位估值，禁用 PE

案例: 江波龙(301308) 2026.7.3 H1预告(归母92-110亿)
  → PE 48x → 21x 骤降，表象"变便宜了"
  → 实际: 180亿存货/GPM 55.5% 周期顶部/CFO/NP=-0.74
  → 高管40亿+减持印证
  → Q2 环比增速(+38-84%)较 Q1(+444% QoQ)明显减速
  → 21x PE 是周期顶部利润制造的"伪安全边际"

防御: 预告后 PE 骤降的强周期股，等 Q3/Q4 数据确认利润可持续性
  Q3 环比增速继续放缓至个位数 → 周期顶部确认，PE 将跳升至 100x+
```

```
CONFIRM: Step E 完成，E_score = [X]/10，周期类型: [强/中/弱/非周期]
```

---

### Step F — 催化剂（10 分/4 类 + 三要素硬约束）

**F1. 四类催化剂**（每类需写明验证时间+渠道）:
```
① 业绩催化: 财报超预期/订单大增/利润率恢复 → 验证点: 季报/中报
② 产品催化: 新品上市/头部客户认证/渗透率提升 → 验证点: 客户公告/调研
③ 客户&业务: 海外客户/并购/产能投产 → 验证点: 公司公告/招标
④ 政策&行业: 补贴落地/产业扶持/国产替代 → 验证点: 政府文件
```

**F2. 硬约束**:
```
- 至少 1 项，最多 3 项核心催化剂
- 每项必须写: 具体事件 + 明确验证时间
- 标注: 短期事件驱动(3个月) vs 中长期逻辑(1-3年)
- 禁止空泛描述（"行业前景向好""有望受益国产替代"）
```

**F3. 失效规则**:
```
催化剂在约定时间未兑现 → 全部投资逻辑重新评估
连续两个催化剂落空 → 考虑减仓
```

```
CONFIRM: Step F 完成，F_score = [X]/10，催化剂: [N] 项
```

---

### Step G — 风险（10 分/单最大风险 + 概率×损失 + 风控）

**G1. 核心风险方向**: 上游原材料涨价/汇率波动/行业价格战/下游资本开支削减/新技术替代/大客户流失/严监管/产能过剩

**G2. 三要素强制模板**:
```
① 单最大风险: [只列一个最致命的]
② 发生概率: [低 0-30% / 中 30-60% / 高 60-100%]
③ 损失幅度: [归母净利润下滑 < 15% / 15-30% / > 30%]
```

**G3. 风控约束**:
```
高概率 + 下滑 > 30%   → 致命风险 → 仓位上限 ≤ 10%
中概率 + 下滑 15-30%  → 重大风险 → 不可重仓
低概率 + 下滑 < 15%   → 温和风险 → 不影响基准
```

**G4. 预警指标前置**:
```
买入前想好观察预警指标（如原材料价格/下游开工率/行业报价）
一旦触发预警 → 提前减仓规避，不等风险兑现
```

```
CONFIRM: Step G 完成，G_score = [X]/10，风险等级: [致命/重大/温和]
```

---

### 统一打分表

| Step | 评分项 | 满分 | 依据 |
|------|--------|------|------|
| A | 生意质量 | 15 | 决定生意天然好坏 |
| B | 护城河 | 20 | 权重最高 — 决定长期估值中枢 |
| C | 增长引擎 | 15 | 决定中期成长性 |
| D | 财务质量 | 20 | 决定盈利真实性 |
| E | 周期位置 | 10 | 决定估值方法选择 |
| F | 催化剂 | 10 | 决定短期爆发力 |
| G | 风险控制 | 10 | 决定下行保护 |
| **合计** | | **100** | |

### 评级-仓位映射

| 分数 | 评级 | 仓位上限 | 说明 |
|------|------|---------|------|
| ≥ 85 | A | 重仓 25-35% | 全方位优秀，B 类壁垒 ≥ 3 |
| 75-84 | B+ | 基准 15-25% | 护城河清晰但生意质量或估值略逊于 A |
| 70-74 | B | 基准 10-20% | 护城河成立但规模/行业位置非龙头 |
| 60-69 | B- | 观察 < 10% | 有亮点但硬伤明显，仅小仓位跟踪 |
| < 60 | C/D | 淘汰 | 不纳入任何仓位 |

### 质量闸门否决权（嵌入评分之上）

```
任何评分 ≥ 85 的标的，必须通过三问闸门:
  Q1: 这个生意的质量配得上这个分数吗？
  Q2: 和同赛道其他标的横向对比如何？
  Q3: 如果是我的钱我会买吗？

任一答案为"否" → 手动降级至观察仓(≤10%)，不执行重仓配置
打分系统 = 定量，质量闸门 = 定性 — 互补而非二选一
```

```
CONFIRM: [5] A-G 完成，总分 = [X]/100，评级 = [A/B+/B/B-/C/D]
```

---

## [6] Q2 2026 预期

```
输入: 卖方研报 + 自主测算

子检查 1: 卖方共识 vs 自主测算
  - 卖方共识（利润/营收预测值 + 来源）
  - 自己测算（基于 Q1 实际 + 行业趋势）
  - 差异在哪

子检查 2: 内生 vs 外生归因
  内生驱动(份额/新品/降本) → 估值溢价 + 加分
  外生驱动(行业景气/原材料降价) → 贝塔红利 + 不加分

子检查 3: 机构预测可信度
  近 2 次财报卖方预测偏差率:
    均 < 10%   → 高可信度
    单次 > 20% → 关注 — 机构看不准
    两次均 > 20% → 低可信度 — 评级自动降一级，以自己测算为准

输出模板:
  ┌─────────────────────────────────────┐
  │ [6] Q2 预期完成                      │
  │ 超/符合/低于预期: [判定]               │
  │ 驱动来源: [内生/外生]                  │
  │ 机构可信度: [高/中/低]                 │
  │ CONFIRM: [6] 完成                     │
  └─────────────────────────────────────┘
```

---

## [7] 估值分析

```
输入: [6] 业绩预期 + Step E 周期类型

子检查 1: 三情景估值
  保守: 绑定具体假设（如"下游需求-10%、ASP降5%"）
  基准: 当前趋势外推
  乐观: 绑定 Step F 可验证催化剂

子检查 2: PE 估值
  - 当前 PE + FY2026E + FY2027E + PEG
  - vs 自身 5 年 PE 中位
  - vs 同赛道同行

子检查 3: PEG 与资本开支联动
  净利润 PEG = PE(TTM) / NP 增速(%)
  FCF PEG = PE(TTM) / FCF 增速(%)
  重资产行业: 以 FCF PEG 为准
    净利润 PEG < 1 但 FCF PEG > 2 → 估值陷阱
  轻资产行业: 净利润 PEG 为准

子检查 4: 绝对估值打底
  非周期品: DCF + PE 双向校验，差异 > 30% → 质疑假设
  强/中周期: PB/PS 分位为主
    PB 分位 < 30% → 偏低(加分)
    PB 分位 > 70% → 偏高(减分)

输出模板:
  ┌─────────────────────────────────────┐
  │ [7] 估值完成                         │
  │ 当前 PE: [X]x  FY26E PE: [Y]x        │
  │ PEG: [X.XX]  FCF PEG: [Y.XX]         │
  │ 三情景估值范围: [保守下限]~[乐观上限]     │
  │ PB 分位: [X]%  PS 分位: [Y]%         │
  │ CONFIRM: [7] 完成                     │
  └─────────────────────────────────────┘
```

---

## [8] 买点分析 & 交易规则

```
输入: [3] 技术面 + [5] 评分 + [7] 估值

子检查 1: 买入区间
  - 基于 MA20/MA30 技术位
  - 优先 TREND_START 信号(MA20 刚拐头向上 + MA30 走平)

子检查 2: 仓位体系（统一引用 PART 4.3 评级-仓位映射）:

  | 评级 | 仓位上限 | 说明 |
  |------|---------|------|
  | A 级 | 重仓 25-35% | 全优，壁垒 ≥ 3 类 |
  | B+ 级 | 基准 15-25% | 护城河清晰 |
  | B 级 | 基准 10-20% | 壁垒成立但非龙头 |
  | B- 级 | 观察 ≤ 10% | 有亮点但硬伤明显 |
  | C 级 | 仅观察 ≤ 5% | 仅保留跟踪价值 |
  | D 级 | 不纳入 | — |

  注: 此为 L4 战略仓位上限。L5 实操仓位 = min(L4_战略上限, L5_定量帽子)。

子检查 3: 加仓双硬约束
  ① 基本面逻辑未证伪: 催化剂仍在有效期内 + 最近一期季报无"低于预期"
  ② 技术面回踩关键支撑企稳: MA20/MA30 缩量回踩 OR TREND_START 重新触发
  绝对禁止浮亏加仓摊薄成本。底仓未盈利前不开加仓。底仓浮盈 > 10% 才能开进攻仓。

子检查 4: 止损双重风控
  绝对止损:
    单只亏损 ≥ 8%（入场价）→ 无条件减仓 50%
    单只亏损 ≥ 12% → 无条件清仓
    触发后 3 个交易日内执行完毕
  技术止损:
    MA30 有效跌破(价在 MA30 以下 + MA30 方向 DOWN) → 触发双确认 B 条件
  两种止损互补: 技术未破但亏损已达 8% → 框架可能看漏，先减再说

子检查 5: 卖出双确认制 (A+B) — 铁律第一条

  A 条件（框架层 v3.1 — 强弱分级）:
    强A(清仓级): z > +1.0 OR z连续两季下行 > 0.15 → 产业周期结束
      任何技术反弹都是卖点，不等B
    弱A(减仓级): Δz < -0.10 OR PE分位 > 90% → 降仓位至正常50%
      保留底仓观察，等B确认后再全额执行
    不触发: L4"过热WARN" = 不加仓，不是卖出。L2"滞胀"=管仓位上限，不是个股去留

  B 条件（技术层 v3.3）:
    触发: 收盘跌破MA20(连续两日) OR MA20拐头下行(5日斜率<0)
    量价验证: 缩量(量<20日均量×0.8)→减仓减半; 放量(>1.5×)→按原比例; 正常→按原规则
    B内部分级:
      强B: MA20拐头下行 → 趋势已坏 → 全清
      弱B: MA20仍在上升 → 按5日斜率四档:
        ≥1.0(强上升): 不执行(93%收复); 0.5~1.0: 减仓25%
        0.1~0.5: 减仓50%; <0.1(极弱): 按强B全清
    恐慌日修正(v3.3): WW<20或CSI300单日跌>3% → 弱B降级为观察等下一日
                      强B不变(趋势本身就坏了)。正常日按原规则
    MACD辅助: 顶背离→B更可信; 底背离→弱B可延迟一级

  仅A不满足B → 设止盈(MA20半仓/MA60全清)，不动手
  仅B不满足A → 按强弱B分级执行
  A+B同时满足 → 执行减仓/清仓
  8% 绝对止损优先于双确认制 — 触发无条件执行

输出模板:
  ┌─────────────────────────────────────┐
  │ [8] 买点分析完成                      │
  │ L4 战略仓位上限: [X]%                 │
  │ 买入区间: [价格范围]                   │
  │ 止损 8%/12%: [价格]/[价格]            │
  │ 加仓条件: [描述]                      │
  │ 卖出 A 条件: [描述]                   │
  │ CONFIRM: [8] 完成                     │
  └─────────────────────────────────────┘
```

---

## [9] Lazy-Check（强制输出，不可总结不可跳过）

```
输出模板（必须逐项填写，不能写"无"或"已覆盖"）:

  ┌─────────────────────────────────────┐
  │ [9] Lazy-Check                      │
  │                                     │
  │ 数据源 + 日期:                       │
  │   - 财务数据: [来源] [日期]           │
  │   - K线数据: [来源] [日期]            │
  │   - 行业数据: [来源] [日期]           │
  │                                     │
  │ 覆盖完整性:                          │
  │   - 页码/季度: [X-Y页] [N 季度]      │
  │   - 缺失指标: [列表]                 │
  │                                     │
  │ 最大担忧（一句话）:                   │
  │   [如果只说一个风险，是...]           │
  │                                     │
  │ 遗漏标注:                            │
  │   [哪些数据想要但没拿到?]              │
  │                                     │
  │ CONFIRM: [9] Lazy-Check 完成          │
  └─────────────────────────────────────┘
```

---

# PART 4 — 铁律与阈值速查

> **设计目的**: 所有分散在 PART 1/2/3 中的规则和数值集中这里。

---

## 4.1 25 条 Iron Rules（IF-THEN 格式）

| # | 触发条件 (IF) | 规则 (THEN) | 归属 |
|---|-------------|------------|------|
| 0 | 执行任何择股任务 | 禁止捷径。每 Stage 输出确认数据。 | 全局 |
| 1 | 全量扫描 | 每只股都扫，禁止代表性抽样 | Stage 1 |
| 2 | 拉 K 线 | 月线 BEFORE 日线 MA20 | Stage 3 |
| 3 | 板块分析 | 子板块拆解 BEFORE 评级 | Stage 6B |
| 4 | Stage 0-5b 内 | 只淘汰，禁止输出评级 | Stage 0-5b |
| 5 | 择股范围定义 | Q1 报告分数决定，禁止主观选行业 | Stage 0 |
| 6 | 概念过滤 | 在拉 K 线之前执行 | Stage 2 |
| 7 | 生命周期标签 | 差异化阈值，非装饰性标签 | Stage 3 |
| 8 | 元数据标签 | MULTI_TRACK+CHAIN_POSITION 一次性标注全局复用 | Stage 2 |
| 9 | 关键词打分 | 不能替代人工精判 | Stage 3 |
| 10 | 趋势分析 | 量价配合是趋势的呼吸 | Stage 3 |
| 11 | Step E = 强周期 | 估值贡献度不可用于强周期品。路径A: PE<15→二次审查。路径B: Q2预告PE骤降≥40%→PB/PS替代 | Stage 3.5/Step E |
| 12 | 放量回调 | 不是买点 | Stage 4 |
| 13 | CFO/NP < 0.5 连续两季 | 淘汰，但三类豁免（产能/备货/项目型） | Stage 3.5/D4 |
| 14 | 低 PE | 不是便宜。强周期禁用绝对 PE，改用 PB/PS（路径A+B）。PE<15+增速<5%→价值陷阱（3.5拦截） | Stage 3.5/Step E |
| 15 | 行业好 | 行业好 ≠ 公司好。计算公式级 z-score 与行业对比 | Step C4 |
| 16 | 多标的同族子赛道 | 总仓位上限 = MAX(各上限) × 1.2 | Stage 7 |
| 17 | 日均成交额 < 3000 万 | max 仓位 = 2% | Stage 7 |
| 18 | 观察清单 | 每只必须附带明确触发条件 | Stage 7 |
| 19 | Lazy-Check | 强制输出，不可总结不可跳过 | [9] |
| 20 | 桌面清洁 | 桌面不得残留临时工作文件。分析 JSON 存档至 股票库/分析记录/{代码}_{日期}_{评级}.json 后删除桌面副本 | 全局 |
| 21 | BK 代码 | 不验证直接提取成分股 → 致命 | Stage 1 |
| 22 | 跳 Stage | 导致赛道归属错误 → 致命。跳一步标注原因+让用户确认 | 全局 |
| 23 | L0 跳过 | 用户说"跳过L0" → L1=L1_SP500×1.0。但 Iron Rule 23 豁免需用户明确指令 | 全局 |
| 24 | 数据完整性 | 12 字段缺一不可。"待拉取/N/A/空白"=违禁词。缺字段→JSON退回不分析 | PART 0.4 |
| 23 | L0 触发 | 必须先运行 ww_indicator.py 获取最新 W&W，禁止使用记忆/SOUL.md 旧读数 | L0 |
| 24 | L0/L2 冲突 | L0(Bullish×1.0) 与 L2(滞胀/通缩/紧信用)方向相反时 → L2不碰清单优先于L0帽子数字。情绪不覆盖宏观方向判断 | L0/L2 |

---

## 4.2 淘汰条件速查表（16 条）

| # | 条件 | 阶段 | 豁免可能 |
|---|------|------|---------|
| 1 | NonRec% > 80% | [0] | 无 |
| 2 | 审计意见非标 | [0] | 无 |
| 3 | 商誉/净资产 > 30% + 审计非标 | [0] | 无（联合触发） |
| 4 | GPM < 12% | Step A | 无（天然上限 C） |
| 5 | CFO/NP < 0.5 连续两季（非三类豁免） | 3.5/D4 | 三类豁免 |
| 6 | PE < 15 + 营收增速 < 5%（非周期品） | Stage 3.5 | 无（价值陷阱） |
| 7 | 强周期 + PE < 15 + 二次审查不通过（路径A） | Stage 3.5 | 需三项全过 |
| 8 | 强周期 + Q2预告PE骤降≥40% + CFO/NP<0.5或QoQ放缓（路径B） | Stage 3.5 | 无（PE骤降陷阱） |
| 9 | ROE < 5% + PE > 40x + 营收增速 > 20%（增长陷阱⑤） | Stage 5b | 重资产行业有豁免路径 |
| 10 | 重资产 + ROE < 10% + 联合审查三条全中（⑧） | Stage 5b | ROE 6-10%+PE<30x→观察 |
| 11 | 日均成交额 < 3000 万 → max 2% | Stage 7 | 无（流动性） |
| 12 | MA20 斜率 < -0.5 + MA30 DOWN | [3] | 无（真DOWN） |
| 13 | 评分 < 60 分 | [5] | 无 |
| 14 | 三阶营收停滞型（1 年 < 5%） | [1] | 无（触发预警） |
| 15 | FCF 连续三年为负（轻资产行业） | [2] | 无 |
| 16 | 机构预测两次偏差均 > 20% → 自动降一级 | [6] | 无 |

---

## 4.3 仓位系数调整表

| 触发条件 | 调整 | 适用 |
|----------|------|------|
| 商誉/净资产 > 30% | A→B+, B+→B, B→C | [0] |
| 3Y 分位 > 80% + 5Y 分位 > 80% | × 0.5 | [3] |
| 套牢盘占比 > 60% | × 0.5 | [3] |
| 真DOWN | 淘汰 | [3] |
| 回调机会 | × 0.3 | [3] |
| 蓄力趋势 | × 0.7 | [3] |
| 追高风险 | × 0.2 | [3] |
| 高概率风险 + 下滑 > 30% | ≤ 10% | Step G |
| 同族子赛道多标的 | MAX(各上限) × 1.2 | Stage 7 |
| 日均成交额 < 3000 万 | ≤ 2% | Stage 7 |

---

## 4.4 全阈值速查

```
=== PE 阈值 ===
PE = 15          // 价值陷阱下界 / 强周期二次审查触发（见 pe15-backtest.md 回测）
PE ≤ 23          // 标准买入上限
PE ≤ 28          // 扩张赛道买入上限 + PEG 须 ≤ 0.7
PE > 40          // 增长陷阱联合触发条件

=== NonRec% 阈值 ===
NonRec < 10%     // 盈利干净
NonRec 10-30%    // 需用扣非 PE/ROE
NonRec > 80%     // 直接淘汰

=== GPM 阈值 ===
GPM > 30%        // 满分（高毛利）
GPM 18-30%       // 合格（天然上限 B+）
GPM 12-18%       // 扣分
GPM < 12%        // 预警（天然上限 C）

=== ROE 阈值 ===
ROE ≥ 20%        // 优质（近3年年化）
ROE < 10%        // 扣分
ROE < 5% + PE > 40x + 营收增速 > 20% → 淘汰

=== 资产负债率红线 ===
制造业/周期: 有息负债/净资产 > 70% → 高风险
消费类: 有息负债/净资产 > 60% → 高风险
重资产豁免: 有息负债/净资产 < 80%（需 CFO/NP > 1）

=== CFO/NP ===
CFO/NP < 0.5 连续两季 → 淘汰/降级（非三类豁免）
CFO/NP > 1 → 利润含金量高

=== 评分阈值 ===
≥ 85 → A 级，仓位 25-35%（全优，壁垒 ≥ 3 类）
75-84 → B+ 级，仓位 15-25%（护城河清晰）
70-74 → B 级，仓位 10-20%（壁垒成立但非龙头）
60-69 → B- 级，观察 ≤10%（有亮点但硬伤明显）
< 60 → C/D 淘汰

=== 技术面阈值 ===
MA20 斜率 < -0.5 + MA30 DOWN → 真DOWN 淘汰
偏离 MA20 > ATR 阈值 → 追高风险
日均换手率 > 10% → 异常活跃

=== 时间阈值 ===
SOUL.md > 3 个交易日 → 重新确认持仓
2 季连续恶化 → GPM/NP 预警
3 年 FCF 为负（轻资产）→ 淘汰
2 次预测偏差 > 20% → 低可信度
```

---

## 4.5 豁免条件速查

```
CFO/NP 三类豁免（Stage 3.5/D4）:
  ① 产能扩张: 固定资产/总资产 > 30% + 在建工程 YoY > 50%
  ② 战略性备货: 存货/总资产 > 40% + 存货 YoY > 营收 YoY
  ③ 项目型确认: 合同负债 YoY > 50%

重资产行业豁免（[0] 债务红线）:
  行业: IDC/电网/机场/高速公路
  条件: CFO/NP > 1
  豁免: 有息负债/净资产 < 80%

以价换量豁免（[1]/Step D）:
  条件: GPM 下行 but 营收增速环比扩大 ≥ 5pp
  逻辑: 主动降价抢份额 ≠ 竞争力弱化

回调机会豁免（[3]）:
  条件: MA20 ↓ but MA30 ↑ + VP_LABEL=CORRECTION(缩量)
  若 MA30 方向 DOWN → 豁免失效，降为真DOWN
```

---

# PART 5 — 执行检查清单

> **执行纪律**: 每完成一项标记 `[x]`，跳过的标注原因。

---

## 5.1 L0-L5 流水线检查清单

```
[ ] L0 — W&W 情绪温度计已运行（ww_indicator.py），压缩系数已获取
[ ] L1 — SP500 风险级别 + L0压缩系数 → L1有效上限已计算
[ ] L2 — 宏观象限: 六象限状态 + 定量帽子 + 不碰清单 (两项独立输出)
[ ] L3 — L3黑名单已加载(5511只, Stage 2.0预过滤) + T1-T4信号确认
[ ] L4 — 全量扫描 Stage 0-7 完成（见 5.2）
[ ] L5 — 交易计划（买点/仓位/止损）已输出
[ ] 漏斗数字链已输出: [S0]→[S1]→[S2]→[S3]→[S3.5]→[S4]→[S5]→[S5b]→[S6A]→[S6B]→[S6C]→[S6.5]→[S7]
```

---

## 5.2 Stage 0-7 全量扫描检查清单

```
[ ] Stage 0  — Q1 分数筛选完成（数字确认）
[ ] Stage 1  — BK 代码已验证 + 全量成分股已提取
[ ] Stage 2  — 概念关联度过滤完成（拉 K 线之前）
[ ] Stage 3  — 月线→周线→日线 三周期完成（顺序不颠倒）
[ ] Stage 3.5 — 周期分类 + PE陷阱(路径A存量+路径B骤降) + CFO/NP豁免 + 价值陷阱
[ ] Stage 4  — 月线透支检验完成
[ ] Stage 5  — 非周期品PE + PEG虚高标记完成
[ ] Stage 5b — 增长陷阱⑤ + 重资产ROE联合审查⑧ 完成
[ ] Stage 6A — 元数据预处理完成（生命周期标签 + 概念权重）
[ ] Stage 6B — 板块细分拆解完成（子赛道归属 + 竞争格局）
[ ] Stage 6C  — NonRec% [0] 闸门 → 7步法 [1]-[9] 完成
[ ] Stage 6.5 — 质量闸门四问完成
[ ] Stage 7  — 仓位 + 流动性 + 子赛道 cap 完成
[ ] 全程 — 未在 Stage 0-5b 出现任何评级词（A/B+/B/B-/C/D）
[ ] 漏斗数字链验证: [S0]→[S1]→[S2]→[S3]→[S3.5]→[S4]→[S5]→[S5b]→[S6A]→[S6B]→[S6C]→[S6.5]→[S7]
```

---

## 5.3 择股7步法 [0]-[9] 检查清单

```
[ ] 模式声明: 框架调用 / 独立执行
[ ] [0] NonRec% 前置校验（独立模式）或标注"框架已执行"
[ ] [1] 8-13季财务拆解 → 增速类型 + 季节性异常 + GPM预警
[ ] [2] 资债+现金流 → 议价权 + FCF + CFO/NP + 合同负债
[ ] [3] 技术面 → 月→周→日线 + 分位 + 筹码 + 仓位系数
[ ] [4] 产业链 → 景气度 + 政策风险 + 对手对标
[ ] [5] Step A — GPM/产品/粘性/议价力/商业模式 (15分)
[ ] [5] Step B — 规模/客户/成本/技术 四壁垒 (20分)
[ ] [5] Step C — 来源/持续性/斜率/贝塔vs阿尔法 (15分)
[ ] [5] Step D — GPM趋势/NP稳定/NonRec/ROE(杜邦) + 重资产容忍 + 增长陷阱⑤ (20分)
[ ] [5] Step E — 四类周期 + 估值强制规则 + 分类错误4型 + PE骤降⑥ (10分)
[ ] [5] Step F — 4类催化剂 + 三要素 + 失效规则 (10分)
[ ] [5] Step G — 单最大风险 + 概率×损失 + 预警指标 (10分)
[ ] [5] 总分: [X]/100 → 评级: [A/B+/B/B-/C/D]
[ ] [5] 质量闸门三问（≥85分必须过）
[ ] [6] Q2预期 → 卖方共识 vs 自主 + 内外生归因 + 机构可信度
[ ] [7] 估值 → 三情景 + PEG(含FCF PEG) + 绝对估值(PB/PS/DCF)
[ ] [8] 买点 → 入场区间 + 三级仓位 + 止损8/12% + 卖出双确认
[ ] [9] Lazy-Check → 数据源 + 覆盖 + 最大担忧 + 遗漏
```

---

# 附录 — 参考文件索引

| 文件 | 用途 |
|------|------|
| `references/bk-extraction-guide.md` | BK 板块成分股提取指南（dat格式+SSHY过滤） |
| `references/` | 全量概念分类、产能周期、z-score 方法论、各赛道扫描记录 |
| `references/a-share-hell-time-catalog.md` | A 股 22 轮地狱时段完整分类(S/A/B/X) |
| `references/pe15-backtest.md` | PE=15 阈值回测验证（2026.7.4 完成，8只强周期股×5年数据） |
| `references/pb-percentile-method.md` | PB 分位计算方法 |
| `scripts/residual_backtest.py` | 残差动量回测脚本 |
| `scripts/pb_percentile.py` | PB 分位计算脚本 |
| `C:\Users\Administrator\Desktop\股票库\L3_滞胀期BK黑名单_v1.2.csv` | L3 滞胀期BK黑名单 — 5511只, SW1/SSHY/GPM三层分类, Stage 2.0预过滤 |
| SOUL.md | 用户持仓 + 偏好记忆（时变数据，3 交易日重新确认） |

---

## 相关 Skill 引用

| Skill | 角色 | 必需性 | 不可用时的降级方案 |
|-------|------|--------|------------------|
| `sp500-risk-control` | L1 仓位上限 | 推荐 | → 默认仓位上限 = 50%，标注"L1 缺失，使用保守默认值" |
| `six-quadrant-model` | L2 宏观象限 | 推荐 | → 跳过 L2，标注"宏观数据缺失"，L3 直接接管 |
| `l3-industry-cycle-timing` | L3 产业择时 | 推荐 | → 用 Stage 3.5 的周期判定替代，标注"L3 缺失，用个股周期替代赛道择时" |
| `a-share-trading-plan` | L5 交易执行 | 推荐 | → 仅输出 L4 战略仓位建议，标注"L5 不可用，请手动执行交易" |
| `a-share-data` | 基础设施 | **必需** | → 无降级方案。若不可用，整个流水线无法启动。 |

## 数据源清单

| 数据 | 推荐来源 | 备选来源 |
|------|---------|---------|
| A股基础信息（代码/名称/SW1/SSHY/市值） | 全市场概念分类表_v3.csv（Hermes 维护） | 东方财富 Choice / Tushare |
| 财务数据（GPM/PE/ROE/营收增速/CFO/NP/NonRec） | a-share-data skill → 东方财富 API | 同花顺 iFinD / Wind |
| K线数据（月线/周线/日线/MA/成交量） | a-share-data skill → 东方财富 API | 掘金量化 / QMT |
| 行业/概念分类 | 全市场概念分类表_v3.csv | 申万研究所 / 同花顺概念板块 |
| 营收分拆权重 | 多赛道权重.json（Hermes 生成） | 财报"主营业务构成"章节手动提取 |
| PB/PS 分位 | scripts/pb_percentile.py（本地脚本） | 东方财富历史估值页面 |
| 宏观/SP500 数据 | L1/L2/L3 对应 skill | FRED / Trading Economics |
| 卖方研报/行业信息 | Web Search（Claude 内置） | 券商研报平台 |

---

> **版本历史**:
> - v1.3 (2026.7.5): Stage 2.0 挂载L3黑名单预过滤 (5511只, 三层分类)。L3角色B从空缺→已建。
> - v1.2 (2026.7.5): L1 v4.1条件介入。L2输出拆分定量+定性(AND关系)。L0/L2冲突仲裁(Iron Rule 24)。传导链嵌入L2。
> - v1.1 (2026.7.5): 新增 L0 W&W 情绪温度计（§1.0）。L1 嵌入 L0 压缩系数 + v4.1条件介入。Bullish区×1.0不压缩。
> - v1.0 (2026.7.5): 合并小齐股市框架 v4.3 + L1-L4 框架 v3.1 + 择股7步法 v1.5.4。
>   修正: 标题重复、⑤⑥编号、转义符、NonRec%去重。新增: [DATA_CHECK]、Stage门控、PART 4/5。
